# Generated by Django 3.1.3 on 2020-12-08 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20201206_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('INACT', 'Inactive')], default='ACT', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_status',
            field=models.CharField(choices=[('IN_PROG', 'Inprogress'), ('DONE', 'Done'), ('TESTING', 'Testing'), ('TESTED', 'Tested'), ('BLOCKED', 'Blocked'), ('TODO', 'Todo')], default='TODO', max_length=15),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('TASK', 'Task'), ('STORY', 'Story'), ('BUG', 'Bug')], default='TASK', max_length=15),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=15),
        ),
        migrations.AddField(
            model_name='issue',
            name='relates_to',
            field=models.ManyToManyField(related_name='_issue_relates_to_+', to='api.Issue'),
        ),
        migrations.CreateModel(
            name='MyTodos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
