# Generated by Django 3.0.5 on 2021-05-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210516_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='display_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='sprint',
            unique_together={('display_id', 'project')},
        ),
    ]
