# Generated by Django 3.0.5 on 2021-05-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210529_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='display_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
