# Generated by Django 3.1.3 on 2020-12-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201208_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='relates_to',
            field=models.ManyToManyField(related_name='_issue_relates_to_+', to='api.Issue'),
        ),
    ]
