# Generated by Django 3.0.5 on 2021-05-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210529_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='display_id',
            field=models.IntegerField(),
        ),
    ]
