# Generated by Django 3.0.5 on 2021-06-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210529_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tagged_projects',
        ),
        migrations.AddField(
            model_name='profile',
            name='tagged_projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='api.Project'),
        ),
    ]
