# Generated by Django 3.1.3 on 2020-12-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201208_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tagged_projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.project'),
        ),
    ]
