# Generated by Django 3.0.5 on 2021-08-21 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210621_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_project', to='api.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('TASK', 'Task'), ('STORY', 'Story'), ('BUG', 'Bug'), ('EPIC', 'Epic')], default='TASK', max_length=15),
        ),
    ]
