# Generated by Django 3.0.5 on 2021-09-11 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210821_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='curr_sprint',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_curr_sprint', to='api.Sprint'),
        ),
    ]
