# Generated by Django 3.1.3 on 2020-12-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201208_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='relates_to',
            field=models.ManyToManyField(blank=True, related_name='_issue_relates_to_+', to='api.Issue'),
        ),
    ]
