# Generated by Django 3.1.3 on 2020-12-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201208_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='description',
            new_name='issue_title',
        ),
    ]
