# Generated by Django 3.0.5 on 2021-09-11 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_project_curr_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_project',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_default_project', to='api.Project'),
        ),
    ]
