# Generated by Django 3.0.5 on 2022-09-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_profile_default_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_title',
            field=models.CharField(max_length=125),
        ),
    ]
