# Generated by Django 3.1.3 on 2020-12-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201208_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_title',
            field=models.CharField(max_length=25),
        ),
    ]
