# Generated by Django 3.0.5 on 2023-02-11 17:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20230211_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
